USE [master]
GO
/****** Object:  Database [MyBills_Core]    Script Date: 5/2/2026 8:19:22 PM ******/
CREATE DATABASE [MyBills_Core]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyBills_Core', FILENAME = N'/var/opt/mssql/data/MyBills_Core.mdf' , SIZE = 139264KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyBills_Core_log', FILENAME = N'/var/opt/mssql/data/MyBills_Core_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO


ALTER DATABASE [MyBills_Core] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyBills_Core].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [MyBills_Core] SET ANSI_NULL_DEFAULT ON 
GO
ALTER DATABASE [MyBills_Core] SET ANSI_NULLS ON 
GO
ALTER DATABASE [MyBills_Core] SET ANSI_PADDING ON 
GO
ALTER DATABASE [MyBills_Core] SET ANSI_WARNINGS ON 
GO
ALTER DATABASE [MyBills_Core] SET ARITHABORT ON 
GO
ALTER DATABASE [MyBills_Core] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [MyBills_Core] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MyBills_Core] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MyBills_Core] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MyBills_Core] SET CURSOR_DEFAULT  LOCAL 
GO
ALTER DATABASE [MyBills_Core] SET CONCAT_NULL_YIELDS_NULL ON 
GO
ALTER DATABASE [MyBills_Core] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MyBills_Core] SET QUOTED_IDENTIFIER ON 
GO
ALTER DATABASE [MyBills_Core] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MyBills_Core] SET  DISABLE_BROKER 
GO
ALTER DATABASE [MyBills_Core] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MyBills_Core] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MyBills_Core] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MyBills_Core] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MyBills_Core] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MyBills_Core] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MyBills_Core] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MyBills_Core] SET RECOVERY FULL 
GO
ALTER DATABASE [MyBills_Core] SET  MULTI_USER 
GO
ALTER DATABASE [MyBills_Core] SET PAGE_VERIFY NONE  
GO
ALTER DATABASE [MyBills_Core] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MyBills_Core] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MyBills_Core] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [MyBills_Core] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MyBills_Core] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'MyBills_Core', N'ON'
GO
ALTER DATABASE [MyBills_Core] SET QUERY_STORE = OFF
GO
/****** Object:  User [GEEK\Billsuser]    Script Date: 5/2/2026 8:19:22 PM ******/
USE [master]
GO
CREATE LOGIN [BillAppUser] WITH PASSWORD=N'**********', DEFAULT_DATABASE=[MyBills_Core], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
use [master];
GO
USE [MyBills_Core]
GO
CREATE USER [BillAppUser] FOR LOGIN [BillAppUser]
GO
USE [MyBills_Core]
GO
ALTER USER [BillAppUser] WITH DEFAULT_SCHEMA=[dbo]
GO
USE [MyBills_Core]
GO
ALTER ROLE [db_datareader] ADD MEMBER [BillAppUser]
GO
USE [MyBills_Core]
GO
ALTER ROLE [db_datawriter] ADD MEMBER [BillAppUser]
GO

/****** Object:  Table [dbo].[Bills]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Bills](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
	[IsComplete] [bit] NOT NULL,
	[IsAutoPaid] [bit] NOT NULL,
 CONSTRAINT [PK_dbo.Bills] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Logs]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Logs](
	[LogId] [int] IDENTITY(1,1) NOT NULL,
	[LogLevel] [int] NOT NULL,
	[TimeStamp] [datetime] NOT NULL,
	[CurrentMethod] [nvarchar](100) NULL,
	[ErrorMessage] [nvarchar](4000) NULL,
	[StackTrace] [nvarchar](max) NULL,
	[UserName] [nvarchar](50) NULL,
 CONSTRAINT [PK_dbo.Logs] PRIMARY KEY CLUSTERED 
(
	[LogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PayDays]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PayDays](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Amount] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_dbo.PayDays] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RecurrenceSchedules]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecurrenceSchedules](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RecurrenceTypeId] [int] NOT NULL,
	[Schedule] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_dbo.RecurrenceSchedules] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RecurrenceTypes]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RecurrenceTypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Type] [nvarchar](200) NULL,
 CONSTRAINT [PK_dbo.RecurrenceTypes] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Name] UNIQUE NONCLUSTERED 
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserBills]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserBills](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BillId] [int] NOT NULL,
	[Day] [int] NOT NULL,
	[Month] [int] NOT NULL,
	[Year] [int] NOT NULL,
	[IsPaid] [bit] NOT NULL,
	[UserId] [int] NOT NULL,
	[RecurrenceScheduleId] [int] NOT NULL,
 CONSTRAINT [PK_dbo.UserBills] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserDetails]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserDetails](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[ProfilePicture] [varbinary](max) NULL,
	[UserId] [int] NOT NULL,
 CONSTRAINT [PK_dbo.UserDetails] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Users]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Users](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](50) NOT NULL,
	[PasswordHash] [nvarchar](100) NOT NULL,
	[CreatedDate] [datetime] NOT NULL,
	[UpdatedDate] [datetime] NOT NULL,
 CONSTRAINT [PK_dbo.Users] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Email] UNIQUE NONCLUSTERED 
(
	[Email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [UQ_Username] UNIQUE NONCLUSTERED 
(
	[Username] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Words]    Script Date: 5/2/2026 8:19:22 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Words](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Word] [nvarchar](10) NOT NULL,
 CONSTRAINT [PK_dbo.Words] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Index [IX_RecurrenceTypeId]    Script Date: 5/2/2026 8:19:22 PM ******/
CREATE NONCLUSTERED INDEX [IX_RecurrenceTypeId] ON [dbo].[RecurrenceSchedules]
(
	[RecurrenceTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_BillId]    Script Date: 5/2/2026 8:19:22 PM ******/
CREATE NONCLUSTERED INDEX [IX_BillId] ON [dbo].[UserBills]
(
	[BillId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_RecurrenceScheduleId]    Script Date: 5/2/2026 8:19:22 PM ******/
CREATE NONCLUSTERED INDEX [IX_RecurrenceScheduleId] ON [dbo].[UserBills]
(
	[RecurrenceScheduleId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserId]    Script Date: 5/2/2026 8:19:22 PM ******/
CREATE NONCLUSTERED INDEX [IX_UserId] ON [dbo].[UserBills]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
/****** Object:  Index [IX_UserId]    Script Date: 5/2/2026 8:19:22 PM ******/
CREATE NONCLUSTERED INDEX [IX_UserId] ON [dbo].[UserDetails]
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RecurrenceSchedules]  WITH NOCHECK ADD  CONSTRAINT [FK_dbo.RecurrenceSchedules_dbo.RecurrenceTypes_RecurrenceTypeId] FOREIGN KEY([RecurrenceTypeId])
REFERENCES [dbo].[RecurrenceTypes] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[RecurrenceSchedules] CHECK CONSTRAINT [FK_dbo.RecurrenceSchedules_dbo.RecurrenceTypes_RecurrenceTypeId]
GO
ALTER TABLE [dbo].[UserBills]  WITH NOCHECK ADD  CONSTRAINT [FK_dbo.UserBills_dbo.Bills_BillId] FOREIGN KEY([BillId])
REFERENCES [dbo].[Bills] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserBills] CHECK CONSTRAINT [FK_dbo.UserBills_dbo.Bills_BillId]
GO
ALTER TABLE [dbo].[UserBills]  WITH NOCHECK ADD  CONSTRAINT [FK_dbo.UserBills_dbo.RecurrenceSchedules_RecurrenceScheduleId] FOREIGN KEY([RecurrenceScheduleId])
REFERENCES [dbo].[RecurrenceSchedules] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserBills] CHECK CONSTRAINT [FK_dbo.UserBills_dbo.RecurrenceSchedules_RecurrenceScheduleId]
GO
ALTER TABLE [dbo].[UserBills]  WITH NOCHECK ADD  CONSTRAINT [FK_dbo.UserBills_dbo.Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserBills] CHECK CONSTRAINT [FK_dbo.UserBills_dbo.Users_UserId]
GO
ALTER TABLE [dbo].[UserDetails]  WITH NOCHECK ADD  CONSTRAINT [FK_dbo.UserDetails_dbo.Users_UserId] FOREIGN KEY([UserId])
REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[UserDetails] CHECK CONSTRAINT [FK_dbo.UserDetails_dbo.Users_UserId]
GO
USE [master]
GO
ALTER DATABASE [MyBills_Core] SET  READ_WRITE 
GO
