# syntax=docker/dockerfile:1
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER $APP_UID
WORKDIR /app
#EXPOSE 8015
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src

COPY ["MyBills.Mvc/MyBills.Mvc.csproj", "MyBills.Mvc/"]
COPY ["MyBills.Core/MyBills.Core.csproj", "MyBills.Core/"]
COPY ["MyBills.Services/MyBills.Services.csproj", "MyBills.Services/"]
COPY ["MyBills.Data/MyBills.Data.csproj", "MyBills.Data/"]
COPY ["MyBills.Domain/MyBills.Domain.csproj", "MyBills.Domain/"]
RUN dotnet restore "MyBills.Mvc/MyBills.Mvc.csproj"

COPY . .
WORKDIR "/src/MyBills.Mvc"
RUN dotnet publish "MyBills.Mvc.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "MyBills.Mvc.dll"]