/*
Post-Deployment Script Template							
--------------------------------------------------------------------------------------
 This file contains SQL statements that will be appended to the build script.		
 Use SQLCMD syntax to include a file in the post-deployment script.			
 Example:      :r .\myfile.sql								
 Use SQLCMD syntax to reference a variable in the post-deployment script.		
 Example:      :setvar TableName MyTable							
               SELECT * FROM [$(TableName)]					
--------------------------------------------------------------------------------------
*/

-- Recurrence Types
MERGE INTO RecurrenceTypes AS Target 
USING (VALUES 
  (1, 'Daily', NULL),   
  (2, 'Weekly', 'System.DayOfWeek'),
  (3, 'Bi-weekly Odd', 'System.DayOfWeek'),
  (4, 'Bi-weekly Even', 'System.DayOfWeek'),
  (5, 'Bi-monthly', 'Tuple<Integer, Integer>'),
  (6, 'Monthly', 'Integer'),
  (7, 'Quarterly', 'Tuple<Tuple<Integer, Integer>, Tuple<Integer, Integer>, Tuple<Integer, Integer>, Tuple<Integer, Integer>>'),
  (8, 'Bi-yearly', 'Tuple<Tuple<Integer, Integer>, Tuple<Integer, Integer>>'),
  (9, 'Yearly', 'Tuple<Integer, Integer>'),
  (10, 'One Time', 'System.DateTime')
) 
AS Source (Id, Name, Type) 
ON Target.Id = Source.Id
-- update matched rows 
WHEN MATCHED THEN 
UPDATE SET Name = Source.Name 
-- insert new rows 
WHEN NOT MATCHED BY TARGET THEN 
INSERT (Name, Type)
VALUES (Name, Type)
-- delete rows that are in the target but not the source 
WHEN NOT MATCHED BY SOURCE THEN 
DELETE;


-- Temp password Words
MERGE INTO Words AS Target 
USING (VALUES 
	(1, 'about'),
	(2, 'search'),
	(3, 'other'),
	(4, 'which'),
	(5, 'their'),
	(6, 'there'),
	(7, 'contact'),
	(8, 'business'),
	(9, 'online'),
	(10, 'first'),
	(11, 'would'),
	(12, 'services'),
	(13, 'these'),
	(14, 'click'),
	(15, 'service'),
	(16, 'price'),
	(17, 'people'),
	(18, 'state'),
	(19, 'email'),
	(20, 'health'),
	(21, 'world'),
	(22, 'products'),
	(23, 'music'),
	(24, 'should'),
	(25, 'product'),
	(26, 'system'),
	(27, 'policy'),
	(28, 'number'),
	(29, 'please'),
	(30, 'support'),
	(31, 'message'),
	(32, 'after'),
	(33, 'software'),
	(34, 'video'),
	(35, 'where'),
	(36, 'rights'),
	(37, 'public'),
	(38, 'books'),
	(39, 'school'),
	(40, 'through'),
	(41, 'links'),
	(42, 'review'),
	(43, 'years'),
	(44, 'order'),
	(45, 'privacy'),
	(46, 'items'),
	(47, 'company'),
	(48, 'group'),
	(49, 'under'),
	(50, 'general'),
	(51, 'research'),
	(52, 'january'),
	(53, 'reviews'),
	(54, 'program'),
	(55, 'games'),
	(56, 'could'),
	(57, 'great'),
	(58, 'united'),
	(59, 'hotel'),
	(60, 'center'),
	(61, 'store'),
	(62, 'travel'),
	(63, 'comments'),
	(64, 'report'),
	(65, 'member'),
	(66, 'details'),
	(67, 'terms'),
	(68, 'before'),
	(69, 'hotels'),
	(70, 'right'),
	(71, 'because'),
	(72, 'local'),
	(73, 'those'),
	(74, 'using'),
	(75, 'results'),
	(76, 'office'),
	(77, 'national'),
	(78, 'design'),
	(79, 'posted'),
	(80, 'internet'),
	(81, 'address'),
	(82, 'within'),
	(83, 'states'),
	(84, 'phone'),
	(85, 'shipping'),
	(86, 'reserved'),
	(87, 'subject'),
	(88, 'between'),
	(89, 'forum'),
	(90, 'family'),
	(91, 'based'),
	(92, 'black'),
	(93, 'check'),
	(94, 'special'),
	(95, 'prices'),
	(96, 'website'),
	(97, 'index'),
	(98, 'being'),
	(99, 'women'),
	(100, 'today'),
	(101, 'south'),
	(102, 'project'),
	(103, 'pages'),
	(104, 'version'),
	(105, 'section'),
	(106, 'found'),
	(107, 'sports'),
	(108, 'house'),
	(109, 'related'),
	(110, 'security'),
	(111, 'county'),
	(112, 'american'),
	(113, 'photo'),
	(114, 'members'),
	(115, 'power'),
	(116, 'while'),
	(117, 'network'),
	(118, 'computer'),
	(119, 'systems'),
	(120, 'three'),
	(121, 'total'),
	(122, 'place'),
	(123, 'download'),
	(124, 'without'),
	(125, 'access'),
	(126, 'think'),
	(127, 'north'),
	(128, 'current'),
	(129, 'posts'),
	(130, 'media'),
	(131, 'control'),
	(132, 'water'),
	(133, 'history'),
	(134, 'pictures'),
	(135, 'personal'),
	(136, 'since'),
	(137, 'guide'),
	(138, 'board'),
	(139, 'location'),
	(140, 'change'),
	(141, 'white'),
	(142, 'small'),
	(143, 'rating'),
	(144, 'children'),
	(145, 'during'),
	(146, 'return'),
	(147, 'students'),
	(148, 'shopping'),
	(149, 'account'),
	(150, 'times'),
	(151, 'sites'),
	(152, 'level'),
	(153, 'digital'),
	(154, 'profile'),
	(155, 'previous'),
	(156, 'events'),
	(157, 'hours'),
	(158, 'image'),
	(159, 'title'),
	(160, 'another'),
	(161, 'shall'),
	(162, 'property'),
	(163, 'class'),
	(164, 'still'),
	(165, 'money'),
	(166, 'quality'),
	(167, 'every'),
	(168, 'listing'),
	(169, 'content'),
	(170, 'country'),
	(171, 'private'),
	(172, 'little'),
	(173, 'visit'),
	(174, 'tools'),
	(175, 'reply'),
	(176, 'customer'),
	(177, 'december'),
	(178, 'compare'),
	(179, 'movies'),
	(180, 'include'),
	(181, 'college'),
	(182, 'value'),
	(183, 'article'),
	(184, 'provide'),
	(185, 'source'),
	(186, 'author'),
	(187, 'press'),
	(188, 'learn'),
	(189, 'around'),
	(190, 'print'),
	(191, 'course'),
	(192, 'canada'),
	(193, 'process'),
	(194, 'stock'),
	(195, 'training'),
	(196, 'credit'),
	(197, 'point'),
	(198, 'science'),
	(199, 'advanced'),
	(200, 'sales')
) 
AS Source (Id, Word) 
ON Target.Id = Source.Id
-- update matched rows 
WHEN MATCHED THEN 
UPDATE SET Word = Source.Word 
-- insert new rows 
WHEN NOT MATCHED BY TARGET THEN 
INSERT (Word)
VALUES (Word)
-- delete rows that are in the target but not the source 
WHEN NOT MATCHED BY SOURCE THEN 
DELETE;
