<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MyBills.Data\MyBills.Data.csproj" />
    <ProjectReference Include="..\MyBills.Domain\MyBills.Domain.csproj" />
  </ItemGroup>

</Project>
